using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;
using System.Windows.Threading;
using System.Windows.Input;
using System.Diagnostics;
using Notatnik.Core;

namespace Notatnik;

public sealed partial class MarkdownEditor
{
    private void HandleLinkClick(object sender, MouseButtonEventArgs e)
    {
        var position = GetPositionFromPoint(e.GetPosition(this), snapToText: false);
        if (position is null || !Selection.IsEmpty) return;
        var offset = TextOffset(position);

        foreach (Match match in Regex.Matches(VisibleText(), @"\[([^\]\r\n]+)\]\((https?://[^)\s]+|mailto:[^)\s]+)\)"))
        {
            if (offset < match.Index || offset > match.Index + match.Length) continue;
            try
            {
                Process.Start(new ProcessStartInfo(match.Groups[2].Value) { UseShellExecute = true });
                e.Handled = true;
            }
            catch
            {
                // Nie przerywaj edycji, jeśli system nie potrafi obsłużyć adresu.
            }
            return;
        }
    }

    private void HandleMarkdownKeys(object sender, KeyEventArgs e)
    {
        if ((Keyboard.Modifiers & ModifierKeys.Control) != 0 && e.Key == Key.Z)
        {
            if ((Keyboard.Modifiers & ModifierKeys.Shift) != 0) RedoContentChange();
            else UndoContentChange();
            e.Handled = true;
            return;
        }
        if ((Keyboard.Modifiers & ModifierKeys.Control) != 0 && e.Key == Key.Y)
        {
            RedoContentChange();
            e.Handled = true;
            return;
        }
        if (IsCodeFocused || SelectionLength != 0) return;

        var source = VisibleText();
        var caret = Math.Clamp(CaretIndex, 0, source.Length);
        var lineStart = caret == 0 ? 0 : source.LastIndexOf('\n', caret - 1) + 1;
        var beforeCaret = source[lineStart..caret].TrimEnd('\r');

        if (e.Key == Key.Tab)
        {
            var lineEnd = source.IndexOf('\n', caret);
            if (lineEnd < 0) lineEnd = source.Length;
            var currentLine = source[lineStart..lineEnd].TrimEnd('\r');
            if (!Regex.IsMatch(currentLine, @"^\s*(?:\d+\.|[-*+]|- \[[ xX]\])(?:\s|$)")) return;

            var leadingSpaces = currentLine.TakeWhile(character => character == ' ').Count();
            if ((Keyboard.Modifiers & ModifierKeys.Shift) != 0)
            {
                var remove = Math.Min(4, leadingSpaces);
                if (remove > 0)
                {
                    Select(lineStart, remove);
                    SelectedText = string.Empty;
                    CaretIndex = Math.Max(lineStart, caret - remove);
                }
            }
            else
            {
                var numberedMarker = Regex.Match(currentLine, @"^(\s*)(\d+)\.");
                if (numberedMarker.Success)
                {
                    var oldLength = numberedMarker.Length;
                    var replacement = numberedMarker.Groups[1].Value + "    1.";
                    Select(lineStart, oldLength);
                    SelectedText = replacement;
                    CaretIndex = caret + replacement.Length - oldLength;
                }
                else
                {
                    Select(lineStart, 0);
                    SelectedText = "    ";
                    CaretIndex = caret + 4;
                }
            }
            e.Handled = true;
            return;
        }

        if (e.Key == Key.Back)
        {
            var marker = Regex.Match(beforeCaret, @"^(\s*(?:\d+\.|[-*+]))(\s?)$");
            if (!marker.Success) return;

            // Pierwszy Backspace usuwa automatyczną spację i wyłącza tryb listy.
            // Kolejne Backspace'y pozostawiamy RichTextBoxowi, aby można było
            // normalnie skasować kropkę, cyfrę albo znak punktora.
            if (marker.Groups[2].Length == 0) return;

            Select(caret - 1, 1);
            SelectedText = string.Empty;
            CaretIndex = caret - 1;
            _cancelledListLineStart = lineStart;
            _autoGeneratedListLineStart = -1;
            e.Handled = true;
            return;
        }

        if (e.Key != Key.Enter) return;

        if (_cancelledListLineStart == lineStart &&
            Regex.IsMatch(beforeCaret, @"^\s*(?:\d+\.|[-*+])$"))
        {
            _cancelledListLineStart = -1;
            _autoGeneratedListLineStart = -1;
            return;
        }

        // Po dopisaniu treści anulowany wcześniej znacznik ponownie staje się
        // zwykłym początkiem listy i Enter powinien utworzyć kolejny element.
        if (_cancelledListLineStart == lineStart) _cancelledListLineStart = -1;

        var numbered = Regex.Match(beforeCaret, @"^(\s*)(\d+)\.\s*(.*)$");
        if (numbered.Success)
        {
            if (numbered.Groups[3].Value.Length == 0 && lineStart == _autoGeneratedListLineStart)
            {
                Select(lineStart, caret - lineStart);
                SelectedText = string.Empty;
                CaretIndex = lineStart;
                _autoGeneratedListLineStart = -1;
                e.Handled = true;
                return;
            }

            if (!long.TryParse(numbered.Groups[2].Value, out var number) || number == long.MaxValue) return;
            var nextNumber = number + 1;
            var continuation = $"\r\n{numbered.Groups[1].Value}{nextNumber}. ";
            Select(caret, 0);
            SelectedText = continuation;
            var nextLineStart = caret + 2;
            CaretIndex = caret + continuation.Length;
            _autoGeneratedListLineStart = nextLineStart;
            e.Handled = true;
            return;
        }

        var checklist = Regex.Match(beforeCaret, @"^(\s*)- \[[ xX]\]\s+(.*)$");
        if (checklist.Success)
        {
            ContinueOrEndList(lineStart, caret, checklist.Groups[2].Value, checklist.Groups[1].Value + "- [ ] ");
            e.Handled = true;
            return;
        }

        var bullet = Regex.Match(beforeCaret, @"^(\s*)([-*+])(?:\s+(.*))?$");
        if (bullet.Success)
        {
            ContinueOrEndList(lineStart, caret, bullet.Groups[3].Success ? bullet.Groups[3].Value : string.Empty, bullet.Groups[1].Value + bullet.Groups[2].Value + " ");
            e.Handled = true;
        }
    }

    private void ContinueOrEndList(int lineStart, int caret, string content, string nextPrefix)
    {
        if (content.Length == 0 && lineStart == _autoGeneratedListLineStart)
        {
            Select(lineStart, caret - lineStart);
            SelectedText = string.Empty;
            CaretIndex = lineStart;
            _autoGeneratedListLineStart = -1;
        }
        else
        {
            var continuation = "\r\n" + nextPrefix;
            Select(caret, 0);
            SelectedText = continuation;
            var nextLineStart = caret + 2;
            CaretIndex = caret + continuation.Length;
            _autoGeneratedListLineStart = nextLineStart;
        }
    }

}
