using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;
using System.Windows.Threading;
using System.Windows.Input;
using System.Diagnostics;
using Notatnik.Core;

namespace Notatnik;

public sealed partial class MarkdownEditor : RichTextBox
{
    private bool _formatting;
    private bool _formatPending;
    private bool _hasVisualFormatting;
    private int _autoGeneratedListLineStart = -1;
    private int _cancelledListLineStart = -1;
    private double _lineSpacingFactor = 1.25d;
    private readonly EditHistory _history = new();
    private int _editDepth;
    private bool _restoring;
    public event EventHandler? ContentChanged;
    public bool CanUndoContent => _history.CanUndo;
    public bool CanRedoContent => _history.CanRedo;
    public bool IsCodeFocused => Document.Blocks.OfType<BlockUIContainer>()
        .Any(block => block.Child is CodeCellControl cell && cell.IsKeyboardFocusWithin);

    public MarkdownEditor()
    {
        IsDocumentEnabled = true;
        Document = new FlowDocument(new Paragraph())
        {
            PagePadding = new Thickness(0),
            Background = Brushes.Transparent
        };
        var paragraphStyle = new Style(typeof(Paragraph));
        paragraphStyle.Setters.Add(new Setter(Block.MarginProperty, new Thickness(0)));
        Document.Resources[typeof(Paragraph)] = paragraphStyle;
        // Native formatting must not become another competing undo history.
        IsUndoEnabled = false;
        _history.Reset(new EditorSnapshot(string.Empty));
        TextChanged += (_, _) =>
        {
            if (_formatting || _restoring || _editDepth > 0) return;
            CommitContentChange();
        };
        // Menu commands aimed at a nested code TextBox must use the same history.
        CommandManager.AddPreviewExecutedHandler(this, (_, e) =>
        {
            if (e.Command == ApplicationCommands.Undo) { UndoContentChange(); e.Handled = true; }
            else if (e.Command == ApplicationCommands.Redo) { RedoContentChange(); e.Handled = true; }
            else if (!IsCodeFocused && !Selection.IsEmpty &&
                     (e.Command == ApplicationCommands.Copy || e.Command == ApplicationCommands.Cut))
            {
                try
                {
                    Clipboard.SetText(SelectedText);
                    if (e.Command == ApplicationCommands.Cut) SelectedText = string.Empty;
                }
                catch (System.Runtime.InteropServices.ExternalException) { /* Clipboard is temporarily busy. */ }
                e.Handled = true;
            }
        });
        CommandManager.AddPreviewCanExecuteHandler(this, (_, e) =>
        {
            if (e.Command == ApplicationCommands.Undo) { e.CanExecute = CanUndoContent; e.Handled = true; }
            else if (e.Command == ApplicationCommands.Redo) { e.CanExecute = CanRedoContent; e.Handled = true; }
        });
        PreviewKeyDown += HandleMarkdownKeys;
        PreviewMouseLeftButtonUp += HandleLinkClick;
    }

    public string Text
    {
        get => SerializeDocument();
        set
        {
            Restore(new EditorSnapshot(value ?? string.Empty));
            _history.Reset(Capture());
        }
    }

    public string PlainText => VisibleText();

    public void Edit(Action action)
    {
        if (_editDepth++ == 0) _history.RememberSelection(Capture());
        try { action(); }
        finally { if (--_editDepth == 0) CommitContentChange(); }
    }

    private void CommitContentChange()
    {
        if (_restoring || _formatting || _editDepth > 0) return;
        if (!_history.Record(Capture())) return;
        QueueFormatting();
        ContentChanged?.Invoke(this, EventArgs.Empty);
        CommandManager.InvalidateRequerySuggested();
    }

    private EditorSnapshot Capture()
    {
        var cells = Document.Blocks.OfType<BlockUIContainer>().Select(b => b.Child).OfType<CodeCellControl>().ToList();
        var index = cells.FindIndex(c => c.IsKeyboardFocusWithin);
        return index >= 0
            ? new EditorSnapshot(Text, cells[index].SelectionStart, cells[index].SelectionLength, index)
            : new EditorSnapshot(Text, SelectionStart, SelectionLength);
    }

    private void Restore(EditorSnapshot state)
    {
        _restoring = true;
        _formatPending = false;
        try
        {
            Document.Blocks.Clear();
            LoadDocument(state.Content);
            _autoGeneratedListLineStart = _cancelledListLineStart = -1;
            FormatMarkdown();
            var cell = state.Cell < 0 ? null : Document.Blocks.OfType<BlockUIContainer>()
                .Select(b => b.Child).OfType<CodeCellControl>().ElementAtOrDefault(state.Cell);
            if (cell is null) { Focus(); Select(state.Start, state.Length); }
            else cell.RestoreSelection(state.Start, state.Length);
        }
        finally { _restoring = false; }
    }

    public int SelectionStart
    {
        get => TextOffset(Selection.Start);
        set
        {
            var point = PointerAt(value);
            Selection.Select(point, point);
        }
    }

    public int SelectionLength
    {
        get => FlowText.Read(Selection.Start, Selection.End).Length;
        set
        {
            var start = Selection.Start;
            var startOffset = TextOffset(start);
            Selection.Select(PointerAt(startOffset), PointerAt(startOffset + Math.Max(0, value)));
        }
    }

    public string SelectedText
    {
        get => FlowText.Read(Selection.Start, Selection.End);
        set => Edit(() => new TextRange(Selection.Start, Selection.End).Text = value);
    }

    public int CaretIndex
    {
        get => TextOffset(CaretPosition);
        set => CaretPosition = PointerAt(value);
    }

    public void Select(int start, int length) => Selection.Select(PointerAt(start), PointerAt(start + length));
    public void Clear() => Text = string.Empty;
    public void UndoContentChange()
    {
        _history.RememberSelection(Capture());
        RestoreHistory(_history.Undo());
    }
    public void RedoContentChange()
    {
        _history.RememberSelection(Capture());
        RestoreHistory(_history.Redo());
    }

    private void RestoreHistory(EditorSnapshot? state)
    {
        if (state is null) return;
        Restore(state);
        ContentChanged?.Invoke(this, EventArgs.Empty);
        CommandManager.InvalidateRequerySuggested();
    }

    public void AddPythonCell() => Edit(() =>
    {
        var cell = CreateCell(string.Empty);
        Document.Blocks.Add(new BlockUIContainer(cell) { Margin = new Thickness(0) });
        // Keep a normal paragraph after the cell so writing can continue outside it.
        AddTextBlock(string.Empty);
        cell.FocusCode();
    });

    public void RefreshMarkdownFormatting()
    {
        _formatPending = false;
        FormatMarkdown();
    }
    public double LineSpacingFactor
    {
        get => _lineSpacingFactor;
        set
        {
            _lineSpacingFactor = Math.Clamp(value, 1d, 2d);
            FormatMarkdown();
        }
    }

    private int TextOffset(TextPointer pointer) => FlowText.Read(Document.ContentStart, pointer).Length;

    private TextPointer PointerAt(int requestedOffset)
    {
        // Binary search WPF symbols instead of rebuilding every prefix, character by character.
        var target = Math.Max(0, requestedOffset);
        var start = Document.ContentStart;
        var low = 0;
        var high = start.GetOffsetToPosition(Document.ContentEnd);
        while (low < high)
        {
            var middle = low + (high - low) / 2;
            var pointer = start.GetPositionAtOffset(middle)!;
            if (TextOffset(pointer) < target) low = middle + 1;
            else high = middle;
        }
        var found = start.GetPositionAtOffset(low) ?? Document.ContentEnd;
        var result = found.GetInsertionPosition(LogicalDirection.Forward);
        return result;
    }

    private string VisibleText()
    {
        var value = FlowText.Read(Document.ContentStart, Document.ContentEnd);
        return value.EndsWith("\r\n", StringComparison.Ordinal) ? value[..^2] : value;
    }

}
